version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      security:
        applies-to: security-updates
        open-pull-requests-limit: 10
      ignore-non-security:
        applies-to: version-updates
        open-pull-requests-limit: 0
