---
daysUntilStale: 14
daysUntilClose: 7
exemptLabels:
  - critical
  - technical debt
staleLabel: stale
markComment: >
  This issue has been automatically marked as `stale` because it has not had
  recent activity. :calendar: It will be _closed automatically_ in one week if no further activity occurs.
closeComment: false
